name: Rtp
version: '1.0'
main: de.winniepat.rtp.Rtp
api-version: '1.21'
load: STARTUP
authors: [ WinniePatGG ]
description: Lobby Plugin
website: https://www.winniepat.de
commands:
  rtp:
    description: Random Teleport
    usage: /rtp
    permission: rtp.use
permissions:
  rtp.use:
    description: Allows use of /rtp
    default: true

  rtp.bypass.cooldown:
    description: Allows bypassing the RTP cooldown
    default: op