name: Rtp
version: '1.0'
main: de.winniepat.rtp.Rtp
api-version: '1.21'
load: STARTUP
authors: [ WinniePatGG ]
description: Lobby Plugin
website: https://www.winniepat.de
commands:
  rtp:
    description: Random Teleport
    usage: /rtp
permissions:
  rtp.bypasscooldown:
    description: Allows bypassing the RTP cooldown
    default: op